In [2]:
import os
import numpy as np
# import sklearn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import sklearn.linear_model
import xgboost
import sklearn.svm
import sklearn.ensemble
%load_ext autoreload
%autoreload 2
from utils import *

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.


# load data to numpy

In [3]:
labels = (
    1521,
    1703,
    1707,
    1729,
    1751,
    1755,
    1837,
    2037,
    2525,
    2526,
)

def get_X_y_path_id(bottleneck_basepath):
    X = []
    y = []
    orig_path = []
    orig_id = []
    for label in labels:
        files_path = get_files_in_dir(os.path.join(bottleneck_basepath, str(label)))
        for file_path in files_path:
            bottleneck_string = open(file_path).read()
            bottleneck_values = [float(s) for s in bottleneck_string.split(',')]    
            X.append(bottleneck_values)
            y.append(label)
            orig_path.append(file_path)
            
            
            orig_id.append(
                os.path.basename(file_path).split('.')[0]
            )

    X = np.array(X)
    y = np.array(y)
    return X, y, orig_path, orig_id


def get_X_path_id(unlabled_bottleneck_basepath):
    X = []
    orig_path = []
    orig_id = []
    files_path = get_files_in_dir(unlabled_bottleneck_basepath)
    for file_path in files_path:
        bottleneck_string = open(file_path).read()
        bottleneck_values = [float(s) for s in bottleneck_string.split(',')]    
        X.append(bottleneck_values)
        orig_path.append(file_path)

        current_orig_id = os.path.basename(file_path).split('.')[0]
        
        orig_id.append(current_orig_id
            
        )

    X = np.array(X)
    return X, orig_path, orig_id

In [3]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/seperated_images_inception_fc')
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2,
    random_state=42,
)
model = sklearn.linear_model.SGDClassifier( )
model.fit(X_train, y_train)


train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print('model: SGD\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model = sklearn.svm.SVC(kernel='linear', C=1)
model.fit(X_train, y_train)


train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SGD	train_score:	0.8367520330137153	test_score:0.7747572815533981
model: SGD	train_score:	0.9991503823279524	test_score:0.8616504854368932


In [6]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2,
    random_state=42,
)
model = sklearn.linear_model.SGDClassifier( )
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SGD\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model = sklearn.svm.SVC(kernel='linear', C=1)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SGD	train_score:	0.9543599257884973	test_score:0.8635014836795252
model: SVC	train_score:	1.0	test_score:0.8798219584569733


In [7]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc_my_extractor')
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2,
    random_state=42,
)
model = sklearn.linear_model.SGDClassifier( )
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SGD\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model = sklearn.svm.SVC(kernel='linear', C=1)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SGD	train_score:	0.8304267161410018	test_score:0.7640949554896143
model: SVC	train_score:	0.7769944341372913	test_score:0.7329376854599406


In [8]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_vgg16_last_conv')
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2,
    random_state=42,
)
model = sklearn.linear_model.SGDClassifier( )
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SGD\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model = sklearn.svm.SVC(kernel='linear', C=1)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SGD	train_score:	0.9981447124304267	test_score:0.7997032640949555
model: SVC	train_score:	1.0	test_score:0.8293768545994066


# on our best one keep working

In [20]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2,
    random_state=42,
    stratify=y,
)
model = sklearn.linear_model.SGDClassifier( )
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SGD\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model = sklearn.svm.SVC(kernel='linear', C=1)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SGD	train_score:	0.9183673469387755	test_score:0.8011869436201781
model: SVC	train_score:	1.0	test_score:0.8694362017804155


In [26]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
model = sklearn.svm.SVC(kernel='linear', C=1)
scores = cross_val_score(model, X, y, cv=5)

print(scores)
print(scores.mean())

[ 0.86303387  0.8637037   0.86962963  0.87481371  0.89387145]
0.873010473496


In [28]:
model = sklearn.ensemble.RandomForestClassifier()
scores = cross_val_score(model, X, y, cv=5)

print(scores)
print(scores.mean())

[ 0.7820324   0.7762963   0.78962963  0.80327869  0.78624813]
0.787497029316


In [30]:
model = xgboost.XGBClassifier()
scores = cross_val_score(model, X, y, cv=5)

print(scores)
print(scores.mean())

[ 0.86156112  0.86074074  0.86518519  0.87928465  0.87892377]
0.869139092362


In [33]:
X_1, y_1, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
X_2, y_2, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_vgg16_last_conv')
y = y_1
X = np.zeros((X_1.shape[0], X_1.shape[1] + X_2.shape[1]))
X[:,:X_1.shape[1]] = X_1
X[:,X_1.shape[1]:] = X_2

model = sklearn.svm.SVC(kernel='linear', C=1)
scores = cross_val_score(model, X, y, cv=5)

print(scores)
print(scores.mean())

[ 0.82621502  0.81925926  0.85333333  0.84500745  0.84005979]
0.836774971396


# Wrong - test leaks to train

In [34]:
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/oversampling_full')
model = sklearn.svm.SVC(kernel='linear', C=1)
scores = cross_val_score(model, X, y, cv=5)

print(scores)
print(scores.mean())

[ 0.97741273  0.97669637  0.97634556  0.97771683  0.978738  ]
0.977381897701


# inception stratified - cross validation

In [41]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
)

X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
model = sklearn.svm.SVC(kernel='linear', C=1)
scores = cross_val_score(model, X, y, cv=skf)

print(scores)
print(scores.mean())


[ 0.88512518  0.86814815  0.88        0.88971684  0.86846039]
0.878290112284


# inception stratified 

In [9]:
from sklearn.model_selection import StratifiedShuffleSplit
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
sss = StratifiedShuffleSplit(
    test_size=0.2,
    random_state=1337,
)

train_index, test_index = next(
    sss.split(np.zeros_like(y), y)
)

X_train = X[train_index]
y_train = y[train_index]
X_test = X[test_index]
y_test = y[test_index]

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))


model: SVC	train_score:	1.0	test_score:0.8931750741839762


In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/my_resnet50/')
sss = StratifiedShuffleSplit(
    test_size=0.2,
    random_state=1337,
)

train_index, test_index = next(
    sss.split(np.zeros_like(y), y)
)

X_train = X[train_index]
y_train = y[train_index]
X_test = X[test_index]
y_test = y[test_index]

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))


model: SVC	train_score:	1.0	test_score:0.8545994065281899


# Inception features + oversampling

In [21]:
from sklearn.model_selection import StratifiedShuffleSplit
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
sss = StratifiedShuffleSplit(
    test_size=0.2,
    random_state=1337,
)

train_index, test_index = next(
    sss.split(np.zeros_like(y), y)
)

X_train = X[train_index]
y_train = y[train_index]
X_test = X[test_index]
y_test = y[test_index]

#oversample train
X_train_more, y_train_more, orig_path, orig_id = get_X_y_path_id('data/bottleneck/join_images_bottleneck_train_oversampling/train')

X_train = np.vstack((X_train, X_train_more))
y_train = np.hstack((y_train, y_train_more))

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))




model: SVC	train_score:	1.0	test_score:0.9213649851632048


In [6]:
X_train, y_train, _, _ = get_X_y_path_id('data/bottleneck/per_label_stratified/train')
X_train_oversampling, y_train_oversampling, _, _ = get_X_y_path_id('data/bottleneck/per_label_stratified/train_oversampling')                                                       
X_valid, y_valid, _, _ = get_X_y_path_id('data/bottleneck/per_label_stratified/validation')

X_train = np.vstack((X_train, X_train_oversampling))
y_train = np.hstack((y_train, y_train_oversampling))

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
valid_score = model.score(X_valid, y_valid)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,valid_score))

model: SVC	train_score:	1.0	test_score:0.8694362017804155


# resnet conv layer

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
X, y, orig_path, orig_id = get_X_y_path_id('data/bottleneck/per_label_resnet50')
sss = StratifiedShuffleSplit(
    test_size=0.2,
    random_state=1337,
)

train_index, test_index = next(
    sss.split(np.zeros_like(y), y)
)

X_train = X[train_index]
y_train = y[train_index]
X_test = X[test_index]
y_test = y[test_index]

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,test_score))

model: SVC	train_score:	0.8315398886827459	test_score:0.5830860534124629


# rebuild best model

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
X, y, _, _ = get_X_y_path_id('data/bottleneck/joined_images_inception_fc')
sss = StratifiedShuffleSplit(
    test_size=0.2,
    random_state=1337,
)

train_index, validation_index = next(
    sss.split(np.zeros_like(y), y)
)
X_train = X[train_index]
y_train = y[train_index]

X_validation = X[validation_index]
y_validation = y[validation_index]

model = sklearn.svm.SVC(
    kernel='linear',
)
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
validation_score = model.score(X_validation, y_validation)

print('model: SVC\ttrain_score:\t{}\ttest_score:{}'.format(train_score,validation_score))

In [ ]:
# predict unlabeld test

In [21]:
X_test, test_files_path, test_samples_id = get_X_path_id('data/bottleneck/unlabled_test_joined')

predictions = model.predict(X_test)

with open('prediction.csv', 'w') as out_file:
    out_file.write('ad_id,image_path,cat_id\n')
    for prediction, test_sample_id in zip(predictions, test_samples_id):
        line = '{},none,{}\n'.format(test_sample_id, prediction)
        out_file.write(line)