In [76]:
from keras import applications
from keras.models import Sequential
from keras.layers import Flatten
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import matplotlib
%load_ext autoreload
%autoreload 2
%matplotlib inline
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
model = applications.VGG16(weights='imagenet', include_top=True)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [20]:
model = applications.VGG16(weights='imagenet', include_top=True)
model.layers.pop()
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [70]:
# load bottleneck features

labels = (
    1521,
    1703,
    1707,
    1729,
    1751,
    1755,
    1837,
    2037,
    2525,
    2526,
)
# for label in label
# for file_path in get_files_in_dir()


# from scipy import misc
# image = misc.imread(file_path)

img_width, img_height = 224, 224
batch_size = 16
image_dir = 'data/per_label_joined/'


#     imgen = ImageDataGenerator(rescale=1. / 255)
#     image_gen = imgen.flow_from_directory(
#         image_dir,
#         target_size=(img_height, img_width),
#         batch_size=batch_size,
#         class_mode='binary',
#     )

#     id_to_label = {value:int(key) for key, value in image_gen.class_indices.items()}
#     images_data, image_labels = yield from images_gen
#     f = np.vectorize(lambda x:id_to_label[int(x)])
    
#     yield images_data, f(image_labels)
    
    
# images_data, image_labels = next(gen_images())
# image_labels()
# print(z)

# print(image_labels)
# imgen.channel_axis

# print(image.shape)
# open(file_path,'rb')
# model.predict()

In [109]:
features

array([[[[   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    0.        ],
         [   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    0.        ],
         [   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    0.        ],
         ..., 
         [   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    5.0688405 ],
         [   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    0.        ],
         [   0.        ,    0.        ,    0.        , ...,    0.        ,
             0.        ,    0.        ]],

        [[   0.        ,    1.61700487,    0.        , ...,   54.96401596,
             0.        ,    0.        ],
         [   0.        ,    0.        ,    0.        , ...,   61.10758972,
             0.        ,   23.42804909],
         [   0.        ,    0.        ,    0.        , 

In [106]:
# _, features.shape

(1, 7, 7, 512)

In [79]:
# from tensorflow.python.platform import gfile

# image_data = gfile.FastGFile(file_path, 'rb').read()

In [110]:
f = features.flatten()

In [111]:
f

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [113]:
f[10:100]

array([  0.        ,   0.        ,  15.84506702,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
        18.99848366,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,  18.20442009,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [114]:
from keras.applications.inception_v3 import InceptionV3
from keras.layers import Input

In [116]:
model = InceptionV3(weights='imagenet', include_top=True)

In [118]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_14 (InputLayer)            (None, None, None, 3) 0                                            
____________________________________________________________________________________________________
conv2d_1 (Conv2D)                (None, None, None, 32 864         input_14[0][0]                   
____________________________________________________________________________________________________
batch_normalization_1 (BatchNorm (None, None, None, 32 96          conv2d_1[0][0]                   
____________________________________________________________________________________________________
activation_1 (Activation)        (None, None, None, 32 0           batch_normalization_1[0][0]      
___________________________________________________________________________________________